// seed-data/badges.js
module.exports = [
  {
    name: 'First Line of Defense',
    icon: '🛡️',
    description: 'Reported your first phishing simulation.',
    criteria: 'Submit one phishing report via the Report Suspicious Email form.',
    points_value: 50,
    tier: 'bronze',
  },
  {
    name: 'Eagle Eye',
    icon: '🔍',
    description: 'Correctly reported five phishing simulations.',
    criteria: '5 verified phishing reports.',
    points_value: 150,
    tier: 'silver',
  },
  {
    name: 'Top Phish Hunter',
    icon: '🏆',
    description: 'Took the #1 spot on the monthly leaderboard.',
    criteria: 'Finish a calendar month at rank 1.',
    points_value: 250,
    tier: 'gold',
  },
  {
    name: 'On Fire',
    icon: '🔥',
    description: 'Reported phish on five consecutive days.',
    criteria: '5-day reporting streak.',
    points_value: 100,
    tier: 'silver',
  },
  {
    name: 'Perfect Month',
    icon: '💯',
    description: 'Zero clicks and 100% report rate for a full month.',
    criteria: 'No clicks + every simulation reported across a calendar month.',
    points_value: 500,
    tier: 'platinum',
  },
  {
    name: 'Security Scholar',
    icon: '🎓',
    description: 'Completed every training module.',
    criteria: 'All active training modules passed at 80% or higher.',
    points_value: 300,
    tier: 'gold',
  },
  {
    name: 'Speed Demon',
    icon: '🚀',
    description: 'Reported a phishing simulation within 60 seconds of receipt.',
    criteria: 'time_to_report_seconds <= 60 on any simulation.',
    points_value: 150,
    tier: 'silver',
  },
  {
    name: 'Shop Floor Guardian',
    icon: '🏭',
    description: 'Completed every OT/shop-floor training module.',
    criteria: 'Pass the OT/shop-floor training set.',
    points_value: 250,
    tier: 'gold',
  },
  {
    name: 'CUI Protector',
    icon: '🔒',
    description: 'Passed the CUI handling training with 100%.',
    criteria: 'Score 100 on the CUI Handling & Protection quiz.',
    points_value: 250,
    tier: 'gold',
  },
  {
    name: 'Insider Threat Sentinel',
    icon: '⚡',
    description: 'Completed insider-threat awareness training.',
    criteria: 'Pass the Recognizing Insider Threats module.',
    points_value: 150,
    tier: 'silver',
  },
];
